openapi: 3.0.2
info:
  version: "v1"
  title: "WEDDING ORGANIZER SERVICE"
  license:
    name: Fartech
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Development
    url: https://localhost:8080/api
tags:
  - name: Authentication
paths:
  /v1/auth/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin
                password:
                  type: string
                  example: admin
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponseSchema"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          token:
                            type: string
                            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjEwZjQ"
        404:
          $ref: "#/components/responses/GenericNotFoundResponse"
        500:
          $ref: "#/components/responses/GenericServerErrorResponse"
      tags:
        - Authentication
components:
  schemas:
    ErrorResponseSchema:
      type: object
      properties:
        code:
          type: integer
          description: Status code of the response
        error:
          type: string
          description: Detailed error type
        message:
          type: string
          description: Human-readable description of the response
    SuccessResponseSchema:
      type: object
      properties:
        code:
          type: string
          description: Status code of the response
          example: "00"
        message:
          type: string
          description: Human-readable description of the response
          example: Request performed successfully

  responses:
    # Error responses
    GenericUnauthorizedResponse:
      description: Authentication token or credentials is missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseSchema"
          examples:
            invalid_credentials:
              $ref: "#/components/examples/InvalidCredentialError"
    GenericForbiddenResponse:
      description: Token or credentials is valid but doesn't have sufficient access permission
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseSchema"
          examples:
            forbidden:
              $ref: "#/components/examples/ForbiddenError"
    GenericServerErrorResponse:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseSchema"
          examples:
            server_error:
              $ref: "#/components/examples/ServerError"
    GenericSuccessResponse:
      description: Generic successful response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SuccessResponseSchema"
          examples:
            success:
              $ref: "#/components/examples/RequestSuccess"
    GenericNotFoundResponse:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseSchema"
          examples:
            not_found:
              $ref: "#/components/examples/ResourceNotFoundError"

  examples:
    InvalidCredentialError:
      summary: Invalid credentials
      value:
        code: "40"
        error: INVALID_CREDENTIALS
        message: Authentication token or credentials is missing or invalid
    ForbiddenError:
      summary: Forbidden
      value:
        code: "41"
        error: FORBIDDEN
        message: Doesn't have sufficient access permission
    ResourceNotFoundError:
      summary: Resource not found
      value:
        code: "42"
        error: RESOURCE_NOT_FOUND
        message: Resource not found
    ServerError:
      summary: Internal server error
      value:
        code: "43"
        error: INTERNAL_SERVER_ERROR
        message: Internal server error
    RequestSuccess:
      summary: Request performed successfully
      value:
        code: "00"
        message: Request performed successfully
